services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fzo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build:
      context: ./vkr_be
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fzo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-net

  frontend:
    build:
      context: ./fzo/fzo
    restart: always
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:

volumes:
  postgres_data: