services:
  db:
    image: postgres:15
    restart: always
    command: postgres -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      POSTGRES_DB: fzo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build:
      context: ./vkr_be
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fzo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-net

  frontend:
    build:
      context: ./fzo/fzo
    container_name: react_frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net:

volumes:
  postgres_data: