FROM node:18 as build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build


FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# добавляем свой nginx конфиг
COPY nginx.conf /etc/nginx/conf.d/default.conf